# -*- coding: utf-8 -*-
"""autori.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mzw7d2onkdrHk5LlF3cGFuPXb8pvFBkc
"""

#import
import re

#user input
sName = input()
len(sName) <= 100 #char limit

# input restrictions

#user_input = sName.split('-')
#for char in user_input:
  #first_letter_list = char[0]
  #print(first_letter_list)
  
#list = re.split('-', sName)
for value in list:
    first_char = list(join(s[:1].upper() for s in list))
    print(first_char)
    
def firstChar(s):
  retrun s[:1]
#name1 = list [0][0]
#name2 = list [0][1]
#name3 = list [0][2]


#100 chr limit ('-'ASCII)
#1st character must be uppercase
#the rest can only be lowercase unless a - is in between the names

#output
#abbreviation of input (all capital)
print(sName)

# .upper

# correct code

#imports
import re
import sys
#input
sName = input()
# output
if len(sName) >= 100: 
  sys.exit()
  if not re.match("^[a-z]*-", sName, flags=re.IGNORECASE):
    sys.exit()
new_name = sName.split('-')
abbrev1 = [word[0] for word in new_name]
print("".join(abbrev1).upper())