# -*- coding: utf-8 -*-
"""carrots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kISwlEjH6TZM5mEMvxdQCgn32LYxuF6q
"""

#imports
#input



N, P = map(int, input().split())

if 1 >= N & P >= 100:
  sys.exit()

for elem in range(N):
  input()
#output
print(P)