# -*- coding: utf-8 -*-
"""freefood.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ShqjAdyCd9xlomVxV4MmjqxJkbrvqWPh
"""

import sys
#input
N = int(input())
if not 1 <= N <= 100:
  sys.exit()
#making range
list1 = []
for x in range(N):
  s, t = list(map(int, input().split()))
  for x in range(s, t+1):
    list1.append(x)
if not 1 <= s <= t <= 365:
  sys.exit()
set(list1)
nList = set(list1)
#output
print(len(nList))

#use list.count(elem) to count elements in list, len(list) for set

