# -*- coding: utf-8 -*-
"""missing numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rvQfq5QGmFKHsBS1zTny-OYdJFSqm3bc
"""

import sys
n = int(input())

if not 1 <= n <= 100:
  sys.exit()
list1 = []

for i in range(n):
  rNumbers = int(input())
  if not 1 <= rNumbers <= 200:
    sys.exit()
  list1.append(rNumbers)

list3 = set(list1)
list2 = list(range(1, max(list3)))

if (set(list2).difference(list3)) == set():
  print("good job")
else:
  new_list = (set(list2).difference(list3))
  print(*sorted(new_list), sep = '\n')