# -*- coding: utf-8 -*-
"""sibice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18oO7c3Oipc84T6oTDj9BnQKeXWrcRhCY
"""



#imports
from math import sqrt

#input
N, W, H = map(int, input().split())
matchList = []
#.rstrip()
for _ in range(N):
  matchList.extend(list(map(int, input().split())))
  
#output
boxLimit = int(sqrt(W * W + H * H))
for element in matchList:
  if boxLimit >= element:
    print("DA")
  else:
    print("NE")