# -*- coding: utf-8 -*-
"""take2stones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UNdSGhIIvYC5CKkJG21hWIrh0eOnobeg
"""

import sys
#input
N = int(input())
if not 1 <= N <= 10000000:
  sys.exit()
#output
if N % 2 == 0:
  print("Bob")
else:
  print("Alice")